### ISSUE TITLE
Config file is not found ./data/config/config.json

### ISSUE THREAD

**Issue by seth100** [kerberos-io/agent#103]
Hi,

I'm using the following `docker-compose.yml` file on my Raspberry Pi 4:

```yml
version: '3.9'

services:
  kerberos_agent1:
    image: "kerberos/agent:latest"
    ports:
      - "8080:80"
    env_file:
      - ./.env
    volumes:
      - /home/raspberry/kerberos/config:/home/agent/data/config
      - /home/raspberry/kerberos/recordings:/home/agent/data/recordings
```

and when I run `docker compose up` I get:

```sh
kerberos_agent1_eufy  | {"level":"error","msg":"Config file is not found ./data/config/config.json, trying again in 5s.","time":"2023-06-02T12:17:47+02:00"}
```

so it seems to be a permission related error.

I tried to run on the *host* the following commands (that were suggested on another issue):

```sh
# tried also 777
sudo chmod -R 755 kerberos
sudo chown 100:101 -R kerberos
```

but no luck!

How can I fix that?
Thanks for your work!
