### ISSUE TITLE
Weird agent to vault issue.

### ISSUE THREAD

**Issue by Christiaan-Mathu** [kerberos-io/agent#113]
Hi all, hope you are well.

I have set up our own agents, that looks like its running fine. 

We also host our own vault on some of our servers. 

I managed to get the agents to upload to the vault and everything looks fine but then after a while when there are a lot of events/videos in a short time the agents starts backing up and then after awhile they completely fail to upload new videos and the logs shows the following 

Agent Log:
`
{"level":"info","msg":"UploadKerberosVault: Uploading to Kerberos Vault (https://ourVault.com/api)","time":"2023-08-10T08:20:06+02:00"}
{"level":"info","msg":"UploadKerberosVault: Upload started for 1691532014_6-967003_Cam 1_200-200-400-400_276_769.mp4","time":"2023-08-10T08:20:06+02:00"}
{"level":"info","msg":"UploadKerberosVault: Upload Failed, file doesn't exists anymore.","time":"2023-08-10T08:20:06+02:00"}
{"level":"error","msg":"HandleUpload: UploadKerberosVault: Upload Failed, file doesn't exists anymore.","time":"2023-08-10T08:20:06+02:00"}
`
Please let me know if there is some more info I can give to try and narrow down what it happening 😄

**Comment by cedricve** [comment]
Thank you for reporting @Christiaan-Mathu. Which Kerberos Agent version are you using?

**Comment by Christiaan-Mathu** [comment]
No problem @cedricve, I have tried multiple versions and the problem still persists, am currently using the latest dev [docker image](https://hub.docker.com/r/kerberos/agent-dev/tags) (kerberos/agent-dev:latest)


<img width="238" alt="image" src="https://github.com/kerberos-io/agent/assets/109146644/2c555934-2465-4d2d-9d6a-08063fee3b81">

**Comment by cedricve** [comment]
Can you run this version [384448d](https://github.com/kerberos-io/agent/releases/tag/384448d), as this resolved an issue with uploading and cleanup.

**Comment by Christiaan-Mathu** [comment]
Will do I will let you know if it fixes the problem, thanks in advance 😄

**Comment by Christiaan-Mathu** [comment]
Oky the majority of the recording are now uploading but there are still some that struggle and saw in the logs that it's getting 500 response from the vault so I checked the vault logs and saw the following error:

```
2023/08/10 08:04:20 [Recovery] 2023/08/10 - 08:04:20 panic recovered:
[GIN] 2023/08/10 - 08:04:20 | 500 |    2.327857ms |    192.168.10.1 | POST     "/api/storage"
[GIN] 2023/08/10 - 08:04:20 | 500 |    2.360449ms |    192.168.10.1 | POST     "/api/storage"
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:260 (0x451515)
/usr/local/go/src/runtime/signal_unix.go:835 (0x4514e5)
/go/pkg/mod/github.com/!eyevinn/mp4ff@v0.35.0/mp4/ftyp.go:85 (0xe98bb0)
/go/src/gitlab.com/kerberos-io/vault/api/mp4/fragmented.go:20 (0xe98ba8)
/go/src/gitlab.com/kerberos-io/vault/api/storage/main.go:279 (0x108aee7)
/go/src/gitlab.com/kerberos-io/vault/api/main.go:235 (0x10cda54)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0xb04414)
/go/pkg/mod/github.com/zsais/go-gin-prometheus@v0.1.0/middleware.go:364 (0xb043f5)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x9434c1)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102 (0x9434ac)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x9425c6)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240 (0x9425a9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x9434c1)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102 (0x9434ac)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x9425c6)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240 (0x9425a9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x941650)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620 (0x9412b8)
/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576 (0x940dfc)
/usr/local/go/src/net/http/server.go:2947 (0x6eb6eb)
/usr/local/go/src/net/http/server.go:1991 (0x6e6906)
/usr/local/go/src/runtime/asm_amd64.s:1594 (0x46eda0)
```

**Comment by cedricve** [comment]
Can you disable mp4 fragmentation? Not sure which cameras your are using but it failed to read. out the fragmented mp4 metadata.

![Screenshot 2023-08-10 at 10 40 09](https://github.com/kerberos-io/agent/assets/1546779/3c23d98f-9603-4c63-ac95-06a1c480c9ee)

**Comment by Christiaan-Mathu** [comment]
Hi @cedricve, I have not enabled it its still disabled on the agents?
<img width="523" alt="image" src="https://github.com/kerberos-io/agent/assets/109146644/ae29e98f-0bfa-4524-8f29-b86ab61804ab">

**Comment by Christiaan-Mathu** [comment]
Here is a sample of my agent with the secrets removed:

```
kerberos-agent1:
    image: "kerberos/agent:384448d"
    restart: always
    ports:
      - "8081:80"
    environment:
      - AGENT_NAME=Cam 1
      - AGENT_USERNAME=admin
      - AGENT_PASSWORD=pass
      - AGENT_TIMEZONE=Africa/Johannesburg
      - AGENT_CAPTURE_IPCAMERA_RTSP=rtsp://192.168.10.2:554/unicast/c1/s1/live
      - AGENT_CAPTURE_IPCAMERA_SUB_RTSP=rtsp://192.168.10.2:554/unicast/c1/s1/live
      - AGENT_CAPTURE_PRERECORDING=2
      - AGENT_CAPTURE_POSTRECORDING=2
      - AGENT_CAPTURE_MAXLENGTH=5
      - AGENT_CAPTURE_PIXEL_CHANGE=150
      - AGENT_CLOUD=kstorage
      - AGENT_KERBEROSVAULT_URI=https://myvault.com/api
      - AGENT_KERBEROSVAULT_ACCESS_KEY=key
      - AGENT_KERBEROSVAULT_SECRET_KEY=secret
      - AGENT_KERBEROSVAULT_PROVIDER=MyLocalMinio
      - AGENT_KERBEROSVAULT_DIRECTORY=office
      - AGENT_REGION_POLYGON=0,50;330,50;330,0;1280,0;1280,720;0,720
```
