### ISSUE TITLE
Raspberry pi - Docker / ONVIF

### ISSUE THREAD

**Issue by unichargepay** [kerberos-io/agent#126]
Hello.
I'm having issues with connecting to my IP Camera using ONVIF protocol.

**System info:**

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
docker version
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:36 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Pretty much used the tutorial for seting up with docker-compose:

```
version: "3.9"
services:
  kerberos-agent1:
    image: "kerberos/agent:latest"
    ports:
      - "8081:80"
    environment:
      - AGENT_NAME=agent1
      - AGENT_CAPTURE_IPCAMERA_ONVIF_XADDR=x.x.x.x:80
      - AGENT_CAPTURE_IPCAMERA_ONVIF_USERNAME=admin
      - AGENT_CAPTURE_IPCAMERA_ONVIF_PASSWORD=megapassword
    volumes:
      - ./agent1/config:/home/agent/data/config
      - ./agent1/recordings:/home/agent/data/recordings
```

The configuration file I'm using is the same as in the tutorial.
[config.json](https://raw.githubusercontent.com/kerberos-io/agent/master/machinery/data/config/config.json)

However, after running compose up, there is an issue with the ONVIF endpoint:
```
{"level":"error","msg":"HandleHeartBeat: error while getting PTZ configurations: target endpoint service not found","time":"2023-11-09T19:49:49+01:00"}
```

Host is in the same network as the IP Camera.
I can ping the camera from the host.

Also I tried to connect to the camera with a ODM tool (ONVIF Device Manager) with the proper credentials and it works:

![image](https://github.com/kerberos-io/agent/assets/146528702/63a36a20-b8ac-4ad6-a299-d1fbe14cd97e)

I have no idea, why this doesn't work.

Not sure, if related, but
I noticed, that any change I do in the web administration, won't get saved.
Only way I can set something up is to write RTSP stuff to config and ONVIF creds as ENVs.

Can, someone, please help me with this?

Thank you, very much.
