### ISSUE TITLE
Websocket disconnected, broken recordings (latest release - ca24133)

### ISSUE THREAD

**Issue by Gh0stExp10it** [kerberos-io/agent#146]
Since the last release (version ca24133) I have problems with the recording of two identical camera models. The model in use is the ‘YI-Home-1080p-Camera’, both of which are connected via RTSP. Basically the connection works, but the video files are broken and cannot be played back. I think this is due to the fact that the Websocket keeps disconnecting from time to time. I can see this in the Kerberos agent interface: Here, the status of the Websocket keeps changing from ‘Connected’ (green) to ‘Disconnected’ (yellow) and back again.

If I switch back to the previous release b67a72b, the video recording works without any problems.

Extract from the Docker-Compose configuration of one camera:
```yaml
---
services:
 kerberos-agent-2:
    image: kerberos/agent:latest
    container_name: kerberos-agent-2
    restart: always
    ports:
      - '8891:80'
    environment:
      - AGENT_NAME=YI-Home-1080p-Camera-No.1
      - AGENT_USERNAME=admin
      - AGENT_PASSWORD=<ChangeMe>
      - AGENT_TIMEZONE=Europe/Berlin
      - AGENT_OFFLINE=true
      - AGENT_CAPTURE_IPCAMERA_RTSP=rtsp://admin:<ChangeMe>@192.168.1.49/ch0_0.h264
      - AGENT_AUTO_CLEAN_MAX_SIZE=1024
      - AGENT_CAPTURE_MAXLENGTH=600
      - AGENT_CAPTURE_LIVEVIEW=true
      - AGENT_CAPTURE_RECORDING=true
      - AGENT_CAPTURE_CONTINUOUS=true
      - AGENT_CAPTURE_MOTION=false
      - AGENT_CAPTURE_SNAPSHOTS=false
      - AGENT_CAPTURE_FRAGMENTED=false
      - LOG_LEVEL=warning
      - LOG_OUTPUT=text
    volumes:
      - '/mnt/disk1/kerberos-recordings/agent-2:/home/agent/data/recordings'
[...]
```
